[package]
name = "unftp-sbe-fs"
version = "0.1.0"
description = "A storage back-end for libunftp, storing files on local disk"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Koen Wilde <koen@chillheid.nl>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
]
edition = "2018"
license = "Apache-2.0"
keywords = ["libunftp", "unftp", "ftp", "ftps", "filesystem"]
categories = ["network-programming"]
documentation = "https://docs.rs/unftp-sbe-fs"
homepage = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-sbe-fs"
repository = "https://github.com/bolcom/libunftp/tree/master/crates/unftp-sbe-fs"
readme = "README.md"

[dependencies]
async-trait = "0.1.42"
libunftp = { version="0.17.0", path="../../"}
tracing = "0.1.23"
tracing-attributes = "0.1.12"
tokio = { version = "1.2.0", features = ["rt", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-stream = "0.1.3"
futures = {version = "0.3.12", features = ["std"]}
path_abs = "0.5.0"

[dev-dependencies]
async_ftp = "5.0.0"
clap = "2.33.3"
slog-term = "2.8.0"
slog-async = "2.6.0"
pretty_assertions = "0.7.1"
tempfile = "3.2.0"
tokio = { version = "1.2.0", features = ["rt-multi-thread"]}
tracing-subscriber = "0.2.15"
more-asserts = "0.2.1"
pretty_env_logger = "0.4.0"
rand = "0.8.3"